//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let entitlements = entitlements()

  var image: image { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.image` struct is generated, and contains static references to 110 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Frame 492`.
    var frame492: RswiftResources.ImageResource { .init(name: "Frame 492", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Symbol`.
    var symbol: RswiftResources.ImageResource { .init(name: "Symbol", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Vector`.
    var vector: RswiftResources.ImageResource { .init(name: "Vector", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_2`.
    var app_icon_2: RswiftResources.ImageResource { .init(name: "app_icon_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_3`.
    var app_icon_3: RswiftResources.ImageResource { .init(name: "app_icon_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_4`.
    var app_icon_4: RswiftResources.ImageResource { .init(name: "app_icon_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_5`.
    var app_icon_5: RswiftResources.ImageResource { .init(name: "app_icon_5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_6`.
    var app_icon_6: RswiftResources.ImageResource { .init(name: "app_icon_6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_7`.
    var app_icon_7: RswiftResources.ImageResource { .init(name: "app_icon_7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_8`.
    var app_icon_8: RswiftResources.ImageResource { .init(name: "app_icon_8", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_main.jpg`.
    var app_icon_mainJpg: RswiftResources.ImageResource { .init(name: "app_icon_main.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `app_icon_main1`.
    var app_icon_main1: RswiftResources.ImageResource { .init(name: "app_icon_main1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_main2`.
    var app_icon_main2: RswiftResources.ImageResource { .init(name: "app_icon_main2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_main3`.
    var app_icon_main3: RswiftResources.ImageResource { .init(name: "app_icon_main3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `banner_splash`.
    var banner_splash: RswiftResources.ImageResource { .init(name: "banner_splash", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `banner_time`.
    var banner_time: RswiftResources.ImageResource { .init(name: "banner_time", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `button_clear_text`.
    var button_clear_text: RswiftResources.ImageResource { .init(name: "button_clear_text", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `button_copy_text`.
    var button_copy_text: RswiftResources.ImageResource { .init(name: "button_copy_text", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon-refresh`.
    var iconRefresh: RswiftResources.ImageResource { .init(name: "icon-refresh", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon-refresh 1`.
    var iconRefresh1: RswiftResources.ImageResource { .init(name: "icon-refresh 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon1_DS2`.
    var icon1_DS2: RswiftResources.ImageResource { .init(name: "icon1_DS2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon2_DS2`.
    var icon2_DS2: RswiftResources.ImageResource { .init(name: "icon2_DS2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon3_DS2`.
    var icon3_DS2: RswiftResources.ImageResource { .init(name: "icon3_DS2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon4_DS2`.
    var icon4_DS2: RswiftResources.ImageResource { .init(name: "icon4_DS2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_app_test`.
    var icon_app_test: RswiftResources.ImageResource { .init(name: "icon_app_test", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_best_offer`.
    var icon_best_offer: RswiftResources.ImageResource { .init(name: "icon_best_offer", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_best_seller`.
    var icon_best_seller: RswiftResources.ImageResource { .init(name: "icon_best_seller", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_camera`.
    var icon_camera: RswiftResources.ImageResource { .init(name: "icon_camera", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_change_tone`.
    var icon_change_tone: RswiftResources.ImageResource { .init(name: "icon_change_tone", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_check_lag`.
    var icon_check_lag: RswiftResources.ImageResource { .init(name: "icon_check_lag", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_check_logo`.
    var icon_check_logo: RswiftResources.ImageResource { .init(name: "icon_check_logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_check_write`.
    var icon_check_write: RswiftResources.ImageResource { .init(name: "icon_check_write", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_close_write`.
    var icon_close_write: RswiftResources.ImageResource { .init(name: "icon_close_write", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_continue`.
    var icon_continue: RswiftResources.ImageResource { .init(name: "icon_continue", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_copy`.
    var icon_copy: RswiftResources.ImageResource { .init(name: "icon_copy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_define`.
    var icon_define: RswiftResources.ImageResource { .init(name: "icon_define", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_discard`.
    var icon_discard: RswiftResources.ImageResource { .init(name: "icon_discard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_done_keyboard`.
    var icon_done_keyboard: RswiftResources.ImageResource { .init(name: "icon_done_keyboard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_emoji_no`.
    var icon_emoji_no: RswiftResources.ImageResource { .init(name: "icon_emoji_no", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_emoji_with`.
    var icon_emoji_with: RswiftResources.ImageResource { .init(name: "icon_emoji_with", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_antonym`.
    var icon_feature_antonym: RswiftResources.ImageResource { .init(name: "icon_feature_antonym", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_change_tone`.
    var icon_feature_change_tone: RswiftResources.ImageResource { .init(name: "icon_feature_change_tone", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_define`.
    var icon_feature_define: RswiftResources.ImageResource { .init(name: "icon_feature_define", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_fix_grammar`.
    var icon_feature_fix_grammar: RswiftResources.ImageResource { .init(name: "icon_feature_fix_grammar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_improve`.
    var icon_feature_improve: RswiftResources.ImageResource { .init(name: "icon_feature_improve", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_make_longer`.
    var icon_feature_make_longer: RswiftResources.ImageResource { .init(name: "icon_feature_make_longer", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_make_shorter`.
    var icon_feature_make_shorter: RswiftResources.ImageResource { .init(name: "icon_feature_make_shorter", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_synonym`.
    var icon_feature_synonym: RswiftResources.ImageResource { .init(name: "icon_feature_synonym", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_translate`.
    var icon_feature_translate: RswiftResources.ImageResource { .init(name: "icon_feature_translate", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_fix_grammar`.
    var icon_fix_grammar: RswiftResources.ImageResource { .init(name: "icon_fix_grammar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_gallery`.
    var icon_gallery: RswiftResources.ImageResource { .init(name: "icon_gallery", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_highlight_ds`.
    var icon_highlight_ds: RswiftResources.ImageResource { .init(name: "icon_highlight_ds", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_lag_english`.
    var icon_lag_english: RswiftResources.ImageResource { .init(name: "icon_lag_english", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_left`.
    var icon_left: RswiftResources.ImageResource { .init(name: "icon_left", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_length_long`.
    var icon_length_long: RswiftResources.ImageResource { .init(name: "icon_length_long", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_length_medium`.
    var icon_length_medium: RswiftResources.ImageResource { .init(name: "icon_length_medium", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_length_short`.
    var icon_length_short: RswiftResources.ImageResource { .init(name: "icon_length_short", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_mic`.
    var icon_mic: RswiftResources.ImageResource { .init(name: "icon_mic", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_on_off`.
    var icon_on_off: RswiftResources.ImageResource { .init(name: "icon_on_off", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_options_user`.
    var icon_options_user: RswiftResources.ImageResource { .init(name: "icon_options_user", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_pick_disable`.
    var icon_pick_disable: RswiftResources.ImageResource { .init(name: "icon_pick_disable", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_pick_enable`.
    var icon_pick_enable: RswiftResources.ImageResource { .init(name: "icon_pick_enable", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_right`.
    var icon_right: RswiftResources.ImageResource { .init(name: "icon_right", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_scan`.
    var icon_scan: RswiftResources.ImageResource { .init(name: "icon_scan", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_send_while`.
    var icon_send_while: RswiftResources.ImageResource { .init(name: "icon_send_while", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_about`.
    var icon_setting_about: RswiftResources.ImageResource { .init(name: "icon_setting_about", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_contact`.
    var icon_setting_contact: RswiftResources.ImageResource { .init(name: "icon_setting_contact", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_email`.
    var icon_setting_email: RswiftResources.ImageResource { .init(name: "icon_setting_email", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_privacy`.
    var icon_setting_privacy: RswiftResources.ImageResource { .init(name: "icon_setting_privacy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_share`.
    var icon_setting_share: RswiftResources.ImageResource { .init(name: "icon_setting_share", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_term`.
    var icon_setting_term: RswiftResources.ImageResource { .init(name: "icon_setting_term", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_star`.
    var icon_star: RswiftResources.ImageResource { .init(name: "icon_star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_three_dots`.
    var icon_three_dots: RswiftResources.ImageResource { .init(name: "icon_three_dots", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tone_brutal`.
    var icon_tone_brutal: RswiftResources.ImageResource { .init(name: "icon_tone_brutal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tone_formal`.
    var icon_tone_formal: RswiftResources.ImageResource { .init(name: "icon_tone_formal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tone_friendly`.
    var icon_tone_friendly: RswiftResources.ImageResource { .init(name: "icon_tone_friendly", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tone_professional`.
    var icon_tone_professional: RswiftResources.ImageResource { .init(name: "icon_tone_professional", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tool_translate`.
    var icon_tool_translate: RswiftResources.ImageResource { .init(name: "icon_tool_translate", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_type_email`.
    var icon_type_email: RswiftResources.ImageResource { .init(name: "icon_type_email", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_type_message`.
    var icon_type_message: RswiftResources.ImageResource { .init(name: "icon_type_message", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_write_top`.
    var icon_write_top: RswiftResources.ImageResource { .init(name: "icon_write_top", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image_categories`.
    var image_categories: RswiftResources.ImageResource { .init(name: "image_categories", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image_premium`.
    var image_premium: RswiftResources.ImageResource { .init(name: "image_premium", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onboarding_7_3`.
    var onboarding_7_3: RswiftResources.ImageResource { .init(name: "onboarding_7_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pop_button`.
    var pop_button: RswiftResources.ImageResource { .init(name: "pop_button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pop_copy`.
    var pop_copy: RswiftResources.ImageResource { .init(name: "pop_copy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pop_delete`.
    var pop_delete: RswiftResources.ImageResource { .init(name: "pop_delete", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pop_send`.
    var pop_send: RswiftResources.ImageResource { .init(name: "pop_send", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pop_share`.
    var pop_share: RswiftResources.ImageResource { .init(name: "pop_share", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `robot6`.
    var robot6: RswiftResources.ImageResource { .init(name: "robot6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `search_dictation`.
    var search_dictation: RswiftResources.ImageResource { .init(name: "search_dictation", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `search_glyph`.
    var search_glyph: RswiftResources.ImageResource { .init(name: "search_glyph", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `splash`.
    var splash: RswiftResources.ImageResource { .init(name: "splash", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `supper_car`.
    var supper_car: RswiftResources.ImageResource { .init(name: "supper_car", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `surrealistic_wallpaper_21_origin 1`.
    var surrealistic_wallpaper_21_origin1: RswiftResources.ImageResource { .init(name: "surrealistic_wallpaper_21_origin 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_back`.
    var tabbar_back: RswiftResources.ImageResource { .init(name: "tabbar_back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_email`.
    var tabbar_email: RswiftResources.ImageResource { .init(name: "tabbar_email", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_explore_dark`.
    var tabbar_explore_dark: RswiftResources.ImageResource { .init(name: "tabbar_explore_dark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_explore_dark 1`.
    var tabbar_explore_dark1: RswiftResources.ImageResource { .init(name: "tabbar_explore_dark 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_gallery_dark`.
    var tabbar_gallery_dark: RswiftResources.ImageResource { .init(name: "tabbar_gallery_dark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_gallery_light`.
    var tabbar_gallery_light: RswiftResources.ImageResource { .init(name: "tabbar_gallery_light", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_generate_dark`.
    var tabbar_generate_dark: RswiftResources.ImageResource { .init(name: "tabbar_generate_dark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_generate_light`.
    var tabbar_generate_light: RswiftResources.ImageResource { .init(name: "tabbar_generate_light", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_home_dark`.
    var tabbar_home_dark: RswiftResources.ImageResource { .init(name: "tabbar_home_dark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_home_light`.
    var tabbar_home_light: RswiftResources.ImageResource { .init(name: "tabbar_home_light", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_model_dark`.
    var tabbar_model_dark: RswiftResources.ImageResource { .init(name: "tabbar_model_dark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_model_light`.
    var tabbar_model_light: RswiftResources.ImageResource { .init(name: "tabbar_model_light", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_setting_dark`.
    var tabbar_setting_dark: RswiftResources.ImageResource { .init(name: "tabbar_setting_dark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_setting_dark 1`.
    var tabbar_setting_dark1: RswiftResources.ImageResource { .init(name: "tabbar_setting_dark 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `titleNav`.
    var titleNav: RswiftResources.ImageResource { .init(name: "titleNav", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 0 properties.
  struct entitlements {
    let comAppleSecurityAppSandbox: Bool = true
    let comAppleSecurityNetworkClient: Bool = true
  }

  /// This `_R.font` struct is generated, and contains static references to 5 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `SFProText-Bold`.
    var sfProTextBold: RswiftResources.FontResource { .init(name: "SFProText-Bold", bundle: bundle, filename: "SF-Pro-Text-Bold.ttf") }

    /// Font `SFProText-Heavy`.
    var sfProTextHeavy: RswiftResources.FontResource { .init(name: "SFProText-Heavy", bundle: bundle, filename: "SF-Pro-Text-Heavy.ttf") }

    /// Font `SFProText-Medium`.
    var sfProTextMedium: RswiftResources.FontResource { .init(name: "SFProText-Medium", bundle: bundle, filename: "SF-Pro-Text-Medium.ttf") }

    /// Font `SFProText-Regular`.
    var sfProTextRegular: RswiftResources.FontResource { .init(name: "SFProText-Regular", bundle: bundle, filename: "SF-Pro-Text-Regular.ttf") }

    /// Font `SFProText-Semibold`.
    var sfProTextSemibold: RswiftResources.FontResource { .init(name: "SFProText-Semibold", bundle: bundle, filename: "SF-Pro-Text-Semibold.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [sfProTextBold, sfProTextHeavy, sfProTextMedium, sfProTextRegular, sfProTextSemibold].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 14 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `MyEmail.json`.
    var myEmailJson: RswiftResources.FileResource { .init(name: "MyEmail", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Plist`.
    var plist: RswiftResources.FileResource { .init(name: "Plist", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Bold.ttf`.
    var sfProTextBoldTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Heavy.ttf`.
    var sfProTextHeavyTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Heavy", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Medium.ttf`.
    var sfProTextMediumTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Regular.ttf`.
    var sfProTextRegularTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Semibold.ttf`.
    var sfProTextSemiboldTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Semibold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `app_icon_1.png`.
    var app_icon_1Png: RswiftResources.FileResource { .init(name: "app_icon_1", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `app_icon_main.jpg`.
    var app_icon_mainJpg: RswiftResources.FileResource { .init(name: "app_icon_main", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `categories.json`.
    var categoriesJson: RswiftResources.FileResource { .init(name: "categories", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `country.json`.
    var countryJson: RswiftResources.FileResource { .init(name: "country", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `test.json`.
    var testJson: RswiftResources.FileResource { .init(name: "test", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `typeOptions.json`.
    var typeOptionsJson: RswiftResources.FileResource { .init(name: "typeOptions", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var main: main { .init(bundle: bundle) }

    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.main.validate()
    }


    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}